name: Build Docker image

on:
  workflow_dispatch:
  pull_request:
    branches: ["main"]

jobs:
  build:
    name: Build docker images
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
      - name: Build API Image
        run: make image
