name: Publish to Dockerhub

on:
  release:
    types: [ published ]

jobs:
  publish:
    name: Build and Publish docker image to dockerhub
    permissions:
      contents: write
      pull-requests: write
      packages: read
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker
        uses: docker/setup-buildx-action@v3
      - name: Login to Dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Log in to Heroku
        run: |
          docker run -e HEROKU_API_KEY=${{ secrets.HEROKU_API_KEY }} heroku/heroku:18 container:login

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Build and publish Docker image for multiple architectures
        run: |
          docker buildx build --platform linux/amd64,linux/arm64/v8,linux/arm/v7,linux/ppc64le,linux/s390x -t daithihearn/electricity-prices:latest -t daithihearn/electricity-prices:${{ github.ref_name }} -t registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/web --push .
      - name: Release the container
        run: |
          docker run -e HEROKU_API_KEY=${{ secrets.HEROKU_API_KEY }} heroku/heroku:18 container:release web --app ${{ secrets.HEROKU_APP_NAME }}